mcneilco/acasclient

- acasclient/acasclient.py
- tests/test_acasclient.py
> Allow passing of label_type and label_kind to get_thing_codes_by_labels and get_saved_entity_codes

- acasclient/acasclient.py
- tests/test_acasclient.py
> Add label_type, label_kind to `get_saved_entity_codes`

- acasclient/acasclient.py
- acasclient/interactions.py
- acasclient/lsthing.py
- setup.py
- tests/test_acasclient.py
- tests/test_lsthing.py
- Copied over the whole LsThing / SimpleLsThing / SimpleLink python data classes
- Made breaking change of DDictValue -> CodeValue since that more accurately represents what the class does (as it was not a true DDictValue) and to prevent confusion.
- Removed dead / unused code
- Added a lot of docstrings with examples
I have not yet added any tests. I will try to add some basic tests but there is a substantial amount covered by this new code so we will not have anywhere close to 100% test coverage.
> Simple LsThings

- acasclient/lsthing.py
- tests/test_lsthing.py
Add logic for jsonifying BlobValue.
Note: I was not not able to run all tests probably because of my setup so I just ran `TestBlobValue` and it passed.
> Add jsonifying of  BlobValue.

- acasclient/lsthing.py
Added a new `client` argument which stores reference to the acasclient. Intended purpose is to use the client for downloading/uploading information from ACAS.
> Add 'client' parameter to SimpleLsThing.

- acasclient/acasclient.py
- tests/test_acasclient.py
- tests/test_lsthing.py
Only added a test for Labels because it would take much more effort to create interactions to query.
> ACAS-132: Expose labels and interactions in advanced_search_ls_things

- acasclient/lsthing.py
Fixed the issue I mentioned [here](https://github.com/mcneilco/acasclient/pull/26#discussion_r706571210).
> SS-35219: Fixed default value for 'metadata' or 'results'

- acasclient/lsthing.py
- tests/test_lsthing.py
> Ability to specify the subject_type and object_type when adding links

- acasclient/ddict.py
- tests/test_lsthing.py
- Reworded the error messages for when an invalid code is passed in and for when a dictionary is completely empty
- Updated unit tests to pass
> Reword codevalue errors to make them more user-friendly and actionable

- tests/test_acasclient.py
Fix issue with tests failing due to bad merge
@bffrost Bad merge on my part causing failures in 1.13.7 tests.
ACAS-273
Ran ACAS client tests locally using latest release/1.13.7 images and acasclient tests.
> Fix from bad merge

- tests/test_acasclient.py
Fixes issue with `requires_basic_cmpd_reg_load` where the experiment wasn't getting reloaded properly if deleted/ignored
Adds constant `BASIC_EXPERIMENT_LOAD_EXPERIMENT_NAME`
Adds test for reloading experiment including setting modified date as part of https://github.com/mcneilco/acas-roo-server/pull/334
ACAS-64
Ran acas client tests.
> Fix issue with requires_basic_experiment_load, add test for reloading experiment

- tests/test_acasclient.py
- tests/test_lsthing.py
> Fixing project thing import path

- acasclient/acasclient.py
- tests/test_acasclient.py
Added delete_ls_thing to acasclient w/ associated test
> Added delete_ls_thing to acasclient

- acasclient/acasclient.py
- tests/test_acasclient.py
- tests/test_acasclient/test_005_swap_parent_structures.sdf
Add `swap_parent_structures` API to acasclient and add tests.
acasclient API to swap two parent structures.
[ACAS-286](https://jira.schrodinger.com/browse/ACAS-286).
[acas PR](https://github.com/mcneilco/acas/pull/969)
[acas-roo-server PR](https://github.com/mcneilco/acas-roo-server/pull/342)
* I ran the existing tests and verified the working in the GUI.
~* I am getting issues with the functionality and when running the tests in cases where the swapping shouldn't happen i.e duplicates are present with some other parent. In the `acas-roo-layer` we aren't getting any duplicates when validating.~
> Add swap_parent_structures API.

- acasclient/acasclient.py
- tests/test_acasclient.py
See https://github.com/mcneilco/acas/pull/1112 for details
ACAS-702
> ACAS-702: Add include analysis group values parameter for faster dependency checks + tests

- acasclient/acasclient.py
- tests/test_acasclient.py
- tests/test_lsthing.py
- Tests for fixing issue with downloading cmpdreg files with uppercase (or mixed case) extensions
- DRYed up some file content comparisons
ACAS-711
ran acasclient tests before and after applying acas-roo-server fixes
> ACAS-711: Tests for downloading cmpdreg file content

- tests/test_acasclient.py
- Adding tests for experiment project restrictions
ACAS-712
> ACAS-704 test project restrictions

- acasclient/acasclient.py
- tests/test_acasclient.py
- Adds methods for getting preferred lot corp names and tests
DISCO-798
> DISCO-798: Preferred lot corp name function and test

- .bumpversion.cfg
- acasclient/acasclient.py
- setup.py
Reverts mcneilco/acasclient#157
> Revert "ACAS-758: Try decoding the file content"

- acasclient/acasclient.py
- tests/test_acasclient.py
- Add parameter raise_on_linked_data to delete_lot with true by default.
- Raises a ValueError if the ere is linked experiment data.
ACAS-745
Added acasclient test
> ACAS-745: Add raise_on_linked_data parameter to delete_lot method
